### ISSUE TITLE
Generated changelog not committed?

### ISSUE THREAD

**Issue by CWSites** [faberNovel/github-changelog-generator-action#2]
At the end of the workflow I get the message `Generated log placed in /github/workspace/CI_CHANGE_LOG.md`, how do I get this to actually be committed/added to the root of the repository? It's not doing me any good inside of the docker container that ran the command.

**Comment by vincentbrison** [comment]
You can simply use another action to commit and push your changes, like https://github.com/github-actions-x/commit

**Comment by CWSites** [comment]
For anyone else that comes to look for this, I ended up going this route and it works great.

```yml
      # https://github.com/marketplace/actions/add-commit
      - name: Commit and Push Changelog
        uses: EndBug/add-and-commit@master
        with:
          add: 'CHANGE_LOG.md'
          default_author: github_actions
          message: 'Update Changelog'
```
